### ISSUE TITLE
Chatbot won't recognize the input due to difference in letter cases

### ISSUE THREAD

**Issue by naimarquis** [thompsonson/ctim#40]
When I tried changing the threat actor name (here, it is originally 'zeon') to 'Zeon', the chatbot started to not recognize the input.

![image](https://github.com/thompsonson/ctim/assets/40513536/0ef72cf4-b90a-49e3-a124-3853c5c3faea)

The following screenshots show that I entered the same input, which is 'zeon', but had different responses. The first response is that there have been no changes made yet on the threat actor name. The latter is when I changed the first letter to a capital 'Z', as in Zeon.

![image](https://github.com/thompsonson/ctim/assets/40513536/e7b7eba0-815c-448e-b96e-17b6b3d67fd6)

Additionally, providing inputs in different cases will result in the chatbot not recognizing the input. (see the following screenshots)

![image](https://github.com/thompsonson/ctim/assets/40513536/bcde7e8f-0b95-4454-99a1-5ed677981934)

The issue is also present in other entries.

**Comment by thompsonson** [comment]
Thanks for posting this @naimarquis. The next time you see or test this, please could you include the information in the drop down ![image](https://github.com/thompsonson/ctim/assets/2087867/ddd0fb02-315c-4039-a8be-72d20c1b46fa)

I'll have a look at the code on the API now as well though. I think it should be ignoring the case.

**Comment by naimarquis** [comment]
Hi @thompsonson,

Kindly see attached screenshots for your reference.

![zeon_1](https://github.com/thompsonson/ctim/assets/40513536/1bf9faa8-4e61-4f6c-9feb-ca7933ab2cbc)
![zeon_2](https://github.com/thompsonson/ctim/assets/40513536/76d47f8b-eaa2-43d2-aac7-73cf1a248802)
![zeon_3](https://github.com/thompsonson/ctim/assets/40513536/d015b25e-b68c-4b8e-932a-30a942ec7481)
![zeon_4](https://github.com/thompsonson/ctim/assets/40513536/e668783b-70b5-40b1-81bc-4943e267e513)


> Thanks for posting this @naimarquis. The next time you see or test this, please could you include the information in the drop down ![image](https://private-user-images.githubusercontent.com/2087867/332857476-ddd0fb02-315c-4039-a8be-72d20c1b46fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDU3MDQsIm5iZiI6MTcxNjQ0NTQwNCwicGF0aCI6Ii8yMDg3ODY3LzMzMjg1NzQ3Ni1kZGQwZmIwMi0zMTVjLTQwMzktYThiZS03MmQyMGMxYjQ2ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDYyMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJlZWYwMjlmM2I1MjEzZjBhNzRhNWM3NDM4OTAwOTI0MGU3MjY4YTk3OTI2NGZhYzY5YzljOWYxZDM4ODFmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8ZKfBG7tGmJvzeLUqvSYEOCkyzr5KBE4DXNPDTxcVUk)
> 
> I'll have a look at the code on the API now as well though. I think it should be ignoring the case.

**Comment by naimarquis** [comment]
It seems that it was also showing different outputs (some are incorrect information).

**Comment by naimarquis** [comment]
> Thanks @naimarquis , that is great to have that information.
> 
> I've deployed a change for you to test, please let me know if it still occurs.
> 
> Please include screenshots either way.
> 
> for reference/linking: #50

Hi @thompsonson ,

It seems that it is still occurring. One thing I noticed is that when the input is all lowercase (e.g. zeon), it outputs the correct information. However, if the cases are different (e.g. zeOn, Zeon, zeON), it shows a different output. 

![zzeon_2](https://github.com/thompsonson/ctim/assets/40513536/0f0e147f-9dd8-482b-81b3-0a47e8e453a9)
![zzeon_1](https://github.com/thompsonson/ctim/assets/40513536/a06e37e3-6f0f-461b-807a-18ba5a8a8469)
